### ISSUE TITLE
Finalize schema for WCAG/508 criteria

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#1]
The finalization of the work started with the [initial draft](https://github.com/GSA/open-product-accessibility-template/issues/37).

**Comment by dmundra** [comment]
@mgifford do we want to add the 508 sections from https://github.com/CivicActions/accessibility/blob/main/VPAT/Drupal9AccessibilityConformanceReport.md to the schema, catalog, and drupal-9.yaml example? I presume yes but wanted to double-check.

**Comment by mgifford** [comment]
I think we should close this issue in favour of https://github.com/GSA/open-product-accessibility-template/issues/14 

And yes, I do think it makes sense to flesh it out, even though in the report we may not want to have it be printed out. 

How do we exclude the latter chapters that aren't relevant to web work?

**Comment by dmundra** [comment]
> I think we should close this issue in favour of #14

Sounds good.

> And yes, I do think it makes sense to flesh it out, even though in the report we may not want to have it be printed out.
> 
> How do we exclude the latter chapters that aren't relevant to web work?

The output can be configured to ignore chapters not provided as they are not required by the schema or catalog. I haven't added that conditional logic but we can tackle that in #15 in the next sprint.
