### ISSUE TITLE
Minimal markdown output templating

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#11]

**Comment by dmundra** [comment]
Taken from #45 look at [Handlebars](https://handlebarsjs.com/) for templating.

**Comment by dmundra** [comment]
@grugnog it seems like Handlebars out of the box is more geared for HTML. Do you know of a sub-package that can template markdown?

**Comment by dmundra** [comment]
@grugnog, never mind it looks like it just works with markdown.

**Comment by grugnog** [comment]
@dmundra a lot of the helpers are kinda HTML specific which is perhaps what threw you off :)

**Comment by dmundra** [comment]
Thanks, @grugnog. Ya, all examples spoke about HTML but once I tried it it worked fine. I guess you can probably create any text with handlebars which is cool.

Anyway, the pull request is up.
