### ISSUE TITLE
Add another OPAT example and demonstrate updating Drupal OPAT

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#111]
Need to add another OPAT example of the repo one that uses the WCAG 2.0/508 catalog.

Also, update a few of the criteria/notes of the Drupal OPAT to show how one keeps an OPAT up to date.

**Comment by farooqzakhilwal** [comment]
@mgifford to update the Drupal VPAT

**Comment by mgifford** [comment]
Possibly https://ckeditor.com/docs/ckeditor4/latest/guide/dev_section508.html

**Comment by mgifford** [comment]
CKEditor is really out of date.

What I was wondering was about the possibility of adding a line, say `source_vpat` that would allow us to just pick one and give attribution.  

Not sure if that would work.

**Comment by dmundra** [comment]
Ya, that field can be optional and rendered in the footer as a link.

**Comment by mgifford** [comment]
Some others
https://www.mediawiki.org/wiki/VPAT_for_MediaWiki
https://docs.moodle.org/311/en/VPAT
https://www.nvaccess.org/docs/vpat_nvda.pdf
https://plone.org/accessibility/plone-5-2-vpat.pdf/view
https://www.stukent.com/all/edify-vpat-voluntary-product-accessibility-template/
https://access.redhat.com/sites/default/files/attachments/openshift-4-vpat.pdf
https://help.openlms.net/wp-content/uploads/2020/06/OpenLMS_Boost_VPAT2.3_2020-04.pdf
https://static.carahsoft.com/concrete/files/1515/5717/0218/Acquia_Cloud__VPAT_v2.0_-_Final_2_27_19.pdf
https://support.vitalsource.com/hc/en-us/articles/203882318-Bookshelf-Online-Voluntary-Product-Accessibility-Template-

**Comment by dmundra** [comment]
@mgifford thanks for the additional links and the govready example. Is this issue done?

**Comment by mgifford** [comment]
I'm wondering if we should add a couple more based on this.  Most procurements aren't going to be just between two products.  Might be useful to have some others to look at.

**Comment by dmundra** [comment]
Sounds good!

**Comment by dmundra** [comment]
@mgifford can you tell me how many more examples you thinking of adding? I want to do the reports update all in one go.

**Comment by mgifford** [comment]
I don't know.. These things are taking a while to pull together.  Would love to have a way to strip out the content, but ya...  PDFs and unstructured HTML...

Might make sense to leave it for this for now.
