### ISSUE TITLE
An ACR should include a feedback loop

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#115]
The current VPAT format doesn't suggest this, but having a feedback mechanism built into the ACR would be really useful. 

There should be tighter engagement between vendors & clients.  

Having a way to include how to share new errors back to the vendor would be great.

That could be 
 - an email - accessibility@apple.com
 - a link to an issue queue - https://github.com/GSA/open-product-accessibility-template/issues
 - or perhaps a description of the process.

Could simply be adding at free-form optional element labelled `feedback_mechanism` with some options in the UI for people to follow. They will need examples since this doesn't currently occur. 

If the government is maintaining an ACR based on the vendors, but with their own findings, then it might be beneficial to be able to submit an ACR report back to the vendor to see that the new issues are identified and either addressed or added to the issue queue.

**Comment by dmundra** [comment]
@mgifford maybe this should be a next sprint priority or should it just be in the backlog?

**Comment by mgifford** [comment]
It seems like an easy option element to include in the next sprint.
