### ISSUE TITLE
Legal disclaimer in the footer?

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#126]
I just realized that the legal disclaimer was in the footer.

```
  </main>
  <footer>
    {{#if legal_disclaimer}}
      <h2>Legal Disclaimer{{#if vendor.company_name}} ({{vendor.company_name}}){{/if}}</h2>
      {{legal_disclaimer}}
    {{/if}}
  </footer>
```

Now I'm not sure what should go in the footer, but I do see the disclaimer as part of the main content semantically. I think this would be more semantically correct. 

```
    {{#if legal_disclaimer}}
      <h2 id="legal-disclaimer">Legal Disclaimer{{#if vendor.company_name}} ({{vendor.company_name}}){{/if}}</h2>
      {{legal_disclaimer}}
    {{/if}}
  </main>
  <footer>
  </footer>
```

The footer could possibly contain copyright information. Or maybe a link back to the GitHub repo with a note like "OPAT is a format maintained by the GSA although the content is the responsibility of the author."

**Comment by dmundra** [comment]
Updated it. Let me know if the footer text in the PR is useful or if needs to be changed.
