### ISSUE TITLE
Style footer differently from the rest of the document

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#128]
The footer is distinct from the rest of the document and probably should be styled differently.

Maybe just a dark grey background with white text?

**Comment by dmundra** [comment]
@mgifford I think dark grey background with white text would look odd. My suggestion is to reduce the font size to 14px for the footer. What do you think?

**Comment by mgifford** [comment]
This needs to be done properly in CSS, but just to ease playing with the design:

```
<footer style="
    top: 5px;
    left: 100%;
    margin-top: 50px;
    border-top: 5px solid #171d22;
    width: 90%;">
    <p style="font-size:80%"><a style="font-color:#cfd8de; font-weight:800;" href="https://github.com/GSA/open-product-accessibility-template">OPAT</a> is a format maintained by the <a style="font-color:#cfd8de; font-weight:800;" href="https://gsa.gov/">GSA</a>. The content is the responsibility of the author.</p>
  </footer>
```

I think this would stand out more than the rest. It is probably more modern to just make it a 100% light grey background.  I do think it has to be more than a smaller font though. Folks will miss that. 

![Screen Shot of mock-up of the footer](https://user-images.githubusercontent.com/116832/130123124-a12d80d6-8aa2-4247-ab4b-d7b51c2ae4bc.png)
