### ISSUE TITLE
Define outreach goals

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#13]
**The outreach goals include:**
- explaining the transition from MS Word based VPATs
- encouraging more clients and vendors to think about adopting the format
- finding industry experts to help us maximize the opportunities with this change
- engaging with existing VPAT developers to better document the process

**Metrics:**
- 2 software vendors
- 1 accessibility vendor (VPAT developer)

**Comment by mgifford** [comment]
Other items might include
 - identify a hashtag for social media ( [#opat](https://twitter.com/search?q=%23opat), [#openpats](https://twitter.com/search?q=%23openpat), [#gsaopat](https://twitter.com/search?q=%23gsaopat))
 - Engage in [AXSChat](http://www.axschat.com) Twitter interview
 - Find other [accessibility podcasts](https://accessibility.civicactions.com/guide/resources#podcasts) to engage with
 - Get listed on [accessibility newsletters](https://accessibility.civicactions.com/guide/resources#newsletters)

**Comment by grugnog** [comment]
Need to include goals for what we want to learn from interested parties - how they create/use VPATs currently etc

**Comment by saz33m** [comment]
Metrics:
2 software vendors
1 VPAT developers

**Comment by mgifford** [comment]
@saz33m I've brought those metrics up to the description at the top and I think we can close this now. As long as:

  accessibility vendor  == VPAT developer

Then this should be fine. 

I think we can close this issue now.
