### ISSUE TITLE
Template HTML output

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#15]
Discuss and implement whether the template should split out each chapter instead of looping over them. Or maybe provide multiple templates.

**Comment by dmundra** [comment]
See comment https://github.com/GSA/open-product-accessibility-template/pull/62#discussion_r679515228 for possible formatting options.

**Comment by dmundra** [comment]
Add links in the output to WCAG, e.g. https://www.w3.org/TR/WCAG20/#content-structure-separation-sequence and https://www.access-board.gov/ict/#E101-general

**Comment by dmundra** [comment]
- [ ] Add conditional logic to remove tables/chapters not included in the OPAT.
