### ISSUE TITLE
Style HTML output

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#16]
Right now there is just markdown, but when there is an HTML version, we'll want to add default CSS to the header. Would make sense to have a blank custom.css file in the header too to allow organizations to easily theme a collection of ACRs.

**Comment by dmundra** [comment]
Create a basic CSS file to go the HTML output. Took the styling from WCAG documentation and GitLab VPAT https://design.gitlab.com/accessibility/vpat. Tomorrow I might try to add accessibility testing of the HTML output.
