### ISSUE TITLE
VPAT searchable index

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#17]
Starting with building an [ACR Library that similar to IBM's list of compliance reports](https://www.ibm.com/able/product_accessibility/).

**Comment by dmundra** [comment]
Using the Datatables library, specifically https://datatables.net/examples/data_sources/ajax.html to create the index page.

Submitted pull request in this repo and the website repo https://github.com/GSA/opat-website/pull/10 so we have a place to see the searchable index.
