### ISSUE TITLE
Identify initial outreach targets

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#19]
Initial list:

- [x] GSA
  - [x] 18F
  - [x] Section508.gov
- [ ] USA Gov
  - [x] Access Board
  - [x] VA
  - [ ] Justice
- [ ] IT Vendors
  - [x] GitHub
  - [x] Adobe
  - [x] Microsoft
- [ ] Accessibility Community/Vendors
  - [x] Deque
  - [x] TestPros
  - [x] Funka
  - [x] IAAP
  - [x] Diamond

Outreach should also be done on:
- [ ] Twitter
- [ ] LinkedIN
- [x] A11ySlack

**Comment by mgifford** [comment]
@grugnog is this intended to be people, agencies, or views? Not sure which outreach targets these are?

**Comment by grugnog** [comment]
@mgifford the approach we discussed was to start with GSA (people, groups, projects etc) in early sprints and expand outward to broader spheres of influence as we go.

**Comment by mgifford** [comment]
Thanks @grugnog 

So perhaps this is a good initial list:

- GSA
  - 18F
  - Section508.gov
- USA Gov
  - Access Board
  - VA
- Vendors
  - GitHub
  - Deque

That seems reasonable for an initial set of organizations to specifically target.  I'd like to also see that we target some outreach on:
- Twitter
- LinkedIN
- A11ySlack

That should be good for outreach targets.

**Comment by farooqzakhilwal** [comment]
Outreach checklist ticket created #109
