### ISSUE TITLE
Test talking points with GSA stakeholders

### ISSUE THREAD

**Issue by grugnog** [GSA/open-product-accessibility-template#20]

**Comment by mgifford** [comment]
Possibly https://github.com/GSA/vpat-digitization/issues/26 should get merged in with this. I think we could use an "outreach" label in order to organize these.

**Comment by mgifford** [comment]
Closing this in favour of https://github.com/GSA/open-product-accessibility-template/issues/26

The internal docs have the talking points beyond the 1 pager.
