### ISSUE TITLE
Create 1 Pager for Outreach

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#26]
Build consistent talking points for socializing the project.

**Comment by mgifford** [comment]
There is an[ early draft up here](https://docs.google.com/document/d/1Lyy_QwBiLwp3v5cE2gIg2ksaD6Me4L8MNDzeRg2c3SA/edit#heading=h.cgprxapvl1xz).

**Comment by farooqzakhilwal** [comment]
[Internal Draft here](https://docs.google.com/document/d/1Lyy_QwBiLwp3v5cE2gIg2ksaD6Me4L8MNDzeRg2c3SA/edit).

[Public draft here](https://docs.google.com/document/d/1zFXOnp7lSdxHx67eXM4P3oBEykRwsRsYQP6oM-oj13E/edit).
