### ISSUE TITLE
Update readme, add contributing and license file to the repo

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#29]
We need a LICENCE.md & have it included to the README.md. This should probably be based on [OSCAL's example](https://github.com/usnistgov/OSCAL/blob/main/LICENSE.md).

We will want to run this by Marc & ensure we are running with a CC or MIT based license. GSA will be doing the same.

We would also like to follow the example of [USWDS in having a CONTRIBUTING.md file](https://github.com/uswds/uswds/blob/develop/CONTRIBUTING.md).

Both should be reflected in the README.md file is that is all that most people read.

**Comment by grugnog** [comment]
Suggest we use the default LICENCE and CONTRIBUTING linked from https://18f.gsa.gov/open-source-policy/ - we should be careful to check any external assets that may have other licenses and call them out (there is an example in the above)

**Comment by mgifford** [comment]
Done.
