### ISSUE TITLE
Create first draft of digital VPAT's JSON Schema

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#37]
Just building the initial template. 

We can build on the [W3C's work for WCAG 2.0](https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag2.json) and later on either [WCAG 2.1](https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag21.json) or from [WCAG-EM's WCAG 2.1](https://github.com/w3c/wcag-em-report-tool/blob/master/app/wcag2spec/wcag2-en.json). 

This will be dependent on the [minimal schema defined here](https://github.com/GSA/open-product-accessibility-template/issues/4) and may be redundant.

**Comment by dmundra** [comment]
@mgifford I presume this is sprint 1.

**Comment by mgifford** [comment]
I was thinking that it would be, but I'm going to defer to @grugnog on this as he's got a better view of the dev strategy.

**Comment by dmundra** [comment]
@mgifford so for the schema we want to define keys with their types like "null", "boolean", "object", "array", "number", or "string" and descriptions. Here are some examples: https://json-schema.org/learn/miscellaneous-examples.html and https://ajv.js.org/guide/getting-started.html

Can you nominate a few of the criteria we want to focus on from the VPAT for this first e2e? One vote was Physical but we can take one that aligns with Drupal.

**Comment by mgifford** [comment]
I've suggested one here https://github.com/GSA/open-product-accessibility-template/issues/4#issuecomment-875558296 but think it depends on how we approach this. I think we need to step back and plan how we are going to approach this and determine what elements from https://github.com/mgifford/openpats are worth bringing over.

**Comment by dmundra** [comment]
Stepping back and planning would be good.
