### ISSUE TITLE
Consumers of this data?

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/open-product-accessibility-template#43]
I learned about this effort via an ACT-IAC meeting.
I'm glad to see an effort around producing open data.

I'm curious, who are the existing or intended consumers of this data?

**Comment by mgifford** [comment]
At the moment we are seeing the primary consumers to be procurement officers who will be just viewing the HTML files that will present something that looks much like what VPATs do now. 

We would like to see these reports collectively to be used in agencies to start having a better understanding of the barriers the software they are using presents to their staff, and their customers. 

Accessibility teams would also be making use of this data, and hopefully contributing to it.
