### ISSUE TITLE
Reviewing the different versions of VPAT for common items and differences

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#46]
- List of components by edition (and chapter?)
- List of chapters by edition
- Any differences between chapters of the same name between editions?

https://github.com/mgifford/openpats/tree/main/VPAT2.4

**Comment by mgifford** [comment]
This has been extended and moved over here https://github.com/GSA/open-product-accessibility-template/tree/main/data/VPAT2.4

I think a bit more can be done to highlight this though.

**Comment by dmundra** [comment]
@mgifford should we move this to Sprint 2? I think that should be fine.

**Comment by mgifford** [comment]
I think this should be ready to review once this PR is committed https://github.com/GSA/open-product-accessibility-template/pull/65
