### ISSUE TITLE
Complete project charter

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#5]
- [x] Slack integrations
- [x] Labels
- [x] Issue templates
- [x] Where to hold discussions

**Comment by farooqzakhilwal** [comment]
Draft ready here: https://docs.google.com/document/d/1XHLAgSBdNV4Ayk1heTy8m6Ka2cHN0BAXPxf8ZbmtiOc/edit#heading=h.u9ka0rxq0cgm

Waiting for input from Owen and Luke.

**Comment by grugnog** [comment]
Made some minor revisions to my entry

**Comment by lukefretwell** [comment]
@farooqzakhilwal looks great!

**Comment by grugnog** [comment]
@farooqzakhilwal I think this can be closed now, right?

**Comment by farooqzakhilwal** [comment]
@grugnog Agreed, it is completed.
