### ISSUE TITLE
Graphical representation of the roadmap.

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#55]
Add details in next stand-up

**Comment by farooqzakhilwal** [comment]
[GSA OPAT Roadmap](https://docs.google.com/presentation/d/1Mv5rPIORUKiYroR475hR1D12OYONsrPezBiBbghEdcA/edit#slide=id.ge548d03562_0_1095)

**Comment by saz33m** [comment]
@farooqzakhilwal The content is spot on. However, we do need in the GSA/TTS slide template. So we can more widely share it.

**Comment by farooqzakhilwal** [comment]
@saz33m sounds good. I will move it over to the GSA/TTS slide template.

**Comment by farooqzakhilwal** [comment]
Updated [GSA OPAT Roadmap here](https://docs.google.com/presentation/d/1RPsazp4vuVAxxBddzVgB5IC7l5onOxc_/edit#slide=id.p1), @saz33m we can take out the title slide if it is not necessary.
