### ISSUE TITLE
1-pager refinement and added to the repo

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#56]
Move the "1 pager" from Google to Markdown ( in /docs ) ~~after approval from @lukefretwell~~

Related to #26

**Comment by mgifford** [comment]
@saz33m any reason to not publish the 1 pager here as a Markdown & PDF version in the /docs folder?

**Comment by mgifford** [comment]
@farooqzakhilwal when this is approved, are you ok with adding it to the /docs folder or do you want me to?

**Comment by farooqzakhilwal** [comment]
@saz33m 1-pager added to Repo [here](https://github.com/GSA/open-product-accessibility-template/blob/main/docs/GSA-OPAT-Public.md)

**Comment by mgifford** [comment]
Also related, I added this description to the project page https://github.com/GSA/open-product-accessibility-template/pull/102
