### ISSUE TITLE
Write project description

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#6]

**Comment by mgifford** [comment]
I've added [more information here to the README in this PR](https://github.com/GSA/open-product-accessibility-template/pull/38/commits/782272207fa8a1e264d4e64d9aa85e0e1fd77b7e). I think this can be extended and formalized when we get the [1 pager down](https://github.com/GSA/open-product-accessibility-template/issues/26).

**Comment by farooqzakhilwal** [comment]
Updated [README](https://github.com/GSA/open-product-accessibility-template#readme)
