### ISSUE TITLE
Create a larger OPAT example, add more criteria to the catalog and test the OPAT CLI, update documentation

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#60]
Take the https://github.com/GSA/open-product-accessibility-template/blob/main/tests/examples/valid.yaml example and build on it. Also, add more criteria to the catalog and then test the CLI.

**Comment by mgifford** [comment]
Now moved to https://github.com/GSA/open-product-accessibility-template/blob/main/opat/drupal-9.yaml

**Comment by mgifford** [comment]
@dmundra just noticing that the valid.yaml file is still there.  To avoid confusion, might be useful to have a README.md file in both the /examples directory & /opat directory to explain what they are there and what files should be included in the future. The /example/README.md should probably mention the /opat directory too.

**Comment by dmundra** [comment]
@mgifford I did document the files in `/tests/examples` in docs/CLI.md. We were eventually thinking of eventually moving items from docs/CLI.md to the top level README.md.

Is docs/CLI.md enough or should I add move local README. I can also add a small file that references the docs file. What do you think?

**Comment by dmundra** [comment]
@mgifford submitted the PR to add more documentation.

Also, thanks to your additions the Drupal example is getting bigger and we are improving the validation and output logic so this issue can be closed when the readme changes merge.
