### ISSUE TITLE
Create GSA/ITI discussion outline

### ISSUE THREAD

**Issue by saz33m** [GSA/open-product-accessibility-template#63]
Meeting is scheduled for Wednesday, August 11⋅11:00am – 12:00pm

Need a brief slide deck outline w/ agenda, asks and objectives of discussion

**Comment by mgifford** [comment]
@saz33m does the GSA have a default deck I can start with?  Would have a bigger impression if we started with one with the weight of the GSA. 

The goal of this meeting I believe is to start the discussion about OPAT and work to get broader adoption. 

Proposed agenda
- Introductions
- Why the GSA needs machine-readable VPATs
- GSA's work on OPAT thus far
- Questions/concerns
- Next steps

What else should we include?

**Comment by mgifford** [comment]
I've updated the slides and am seeking feedback.
