### ISSUE TITLE
Define project roadmap

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#7]
Create an initial roadmap for building the 
- OPAT JSON Schema
- HTML/CSS template 
- YAML -> Markdown
- accessibility conformance reports editor (styled on WCAG-EM) 
- validator
- Engagement with stakeholders

**Comment by dmundra** [comment]
The roadmap could match the sprint priorities we outlined in the presentation?
1. Milestones and initial schema and catalog drafts
2. Refined schema and YAML conversion code
3. Themed HTML report
4. Validation code
5. Test CI and validation
6. Web Directory 

Thoughts?

**Comment by mgifford** [comment]
This is what I was thinking. Although, if we want something that validates from the start we may need to reconsider this. 

@grugnog should we update this approach?

**Comment by dmundra** [comment]
Note my added roadmap is more technical so I think we just need to combine the two.

**Comment by dmundra** [comment]
Maybe add a fleshed-out `ROADMAP.md` file to the repo?

**Comment by dmundra** [comment]
Combine roadmap

- Milestones documented, project description, and initial OPAT schema and catalog drafts.
- Refine the OPAT schema and provide YAML to JSON conversion code.
- OPAT schema validation code.
- Continuous integration for the validation code.
- Define outreach goals and targets.
- Markdown output and themed HTML output.
- Outreach and engagement with stakeholders.
- Web directory listing of available OPATs.

**Comment by dmundra** [comment]
@mgifford, @farooqzakhilwal, @grugnog needs review. I can copy it to a roadmap file once we confirm it and update it in the project charter.
