### ISSUE TITLE
Moving adherence conformance level from schema to catalog

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#70]
Right now it is in the `opat-0.1.0.json` as an 'enum' and should be in the catalog. Would need to update validation and output.

**Comment by grugnog** [comment]
Can also move this content from the template to the catalog also (so key, name and description for each level):
```
# Terms
The terms used in the Conformance Level information are defined as follows:
- __Supports__: The functionality of the product has at least one method that meets the criterion without known defects or meets with equivalent facilitation.
- __Partially Supports__: Some functionality of the product does not meet the criterion.
- __Does Not Support__: The majority of product functionality does not meet the criterion.
- __Not Applicable__: The criterion is not relevant to the product.
- __Not Evaluated__: The product has not been evaluated against the criterion. This can be used only in WCAG 2.0 Level AAA.
```

**Comment by dmundra** [comment]
Note: whether the catalog validation should check for duplicate id, alt_id

**Comment by dmundra** [comment]
In the PR, updated validation and output to track the 'terms' in the catalog instead of the schema. Also, included improvement of output tests.

> Note: whether the catalog validation should check for duplicate id, alt_id

Thought about that for a little bit more and realized lower priority/down the road item. Too much for this ticket.
