### ISSUE TITLE
Working for alignment with the W3C

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#74]
Coming from https://github.com/GSA/open-product-accessibility-template/pull/73 and the change to catalog/2.4-edition-508-wcag-2.0.yaml I would propose more closely aligning with the W3C's variable conventions:

- Rather than using "label" let's use W3C's use of "handle"
- Rather than using "key" let's use "alt_id"
- Let's fix up the confusion in "id" in OPAT - "1.3.3" with the id from the W3C - "WCAG2:sensory-characteristics"

Would. make sure that the label (handle) doesn't include either the id or the level.

We can pull information from the W3C's data (JSON -> YAML files) if needed for presentation but validation for OPAT should focus on base identification information.

**Comment by dmundra** [comment]
> Let's fix up the confusion in "id" in OPAT - "1.3.3" with the id from the W3C - "WCAG2:sensory-characteristics"

@mgifford I thought we should change "id" to "num" to match the "num" from the OPAT yaml? Can you say more about the id from the W3C?
