### ISSUE TITLE
MVP Directory listing discovery

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#78]
Maybe use the website repo and thinking filtering/searching the list of the list.

**Comment by mgifford** [comment]
Makes me think that we are going to need to include at least one more .yaml file before we can properly test this.

**Comment by dmundra** [comment]
Created #111 for the other example OPAT addition.

**Comment by dmundra** [comment]
Discovery thoughts:
* Create an index page that uses JavaScript and HTML to list all available OPATs in a directory.
  * The page can allow text search on the fields we display.
  * Maybe typescript compiles/renders the JavaScript/HTML page?
* The page code could live in this repo but then be deployed to the website repo?

Tackled in #17 

Need to find some examples.

**Comment by dmundra** [comment]
A couple of options:
* https://datatables.net/examples/data_sources/ajax (accessible, JSON support)
* https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxdatatable/index.htm
* http://js-grid.com/

**Comment by mgifford** [comment]
Whichever we choose, it would also be important to consider localization and of course accessibility. Also needs to have the right liscense. 

I added to a Navigator question on JSGrid.  Not sure how much accessibility work has been done there.

Noticed this one [jqwidgets has an accessibility statement](https://www.jqwidgets.com/jquery-widgets-documentation/documentation/accessibility/jqwidgets-accessibility-overview.htm?search=) but wish it had a GitHub page to search the issue queue. 

DataTables has similar issues with jqwidgets in that I can't see something like their GitHub issue queue.  Nice to see references in the docs to accessibility tough, but no over-all section.

**Comment by dmundra** [comment]
Thanks, @mgifford for the review of the tools. I was definitely looking to make sure their demos were accessible. I like that jqwidgets has an accessibility statement so let's go with that. Also, I am not opposed to creating an HTML table from scratch and add JavaScript that can filter on it but I think we can avoid that and make sure the content is accessible.

@grugnog any thoughts on this?
