### ISSUE TITLE
Define product vision

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#8]
Based on the project description "This project will develop a digital product accessibility template minimum viable product (MVP) based on Section 508 requirements to enable machine-readable documentation of accessibility conformance and support automated accessibility testing."

We should determine how much we want to extend that.

**Comment by mgifford** [comment]
I didn't add a vision here, but did [add an approach in this PR](https://github.com/GSA/open-product-accessibility-template/pull/38/commits/782272207fa8a1e264d4e64d9aa85e0e1fd77b7e).

I think the vision should be short and held in the README.md file.  It will also likely depend on the [1 pager](https://github.com/GSA/open-product-accessibility-template/issues/26).

**Comment by grugnog** [comment]
Add "Vision" section to README to describe our solution to the problem (described in the context) in a high-level non-technical way.

**Comment by farooqzakhilwal** [comment]
Vision: to "develop a digital product accessibility template minimum viable product (MVP) based on Section 508 requirements to enable machine-readable documentation of accessibility conformance and support automated accessibility testing."

@mgifford how do we say above in a non-technical way?

**Comment by mgifford** [comment]
Our goal is to make it easier for organizations to make good decisions regarding accessibility when buying digital. 

By making accessibility conformance reports machine-readable, will help:
- buyers compare solutions
- managers evaluate what interfaces may limit their staff
- executives better understand the risks of present digital interfaces
