### ISSUE TITLE
Markdown to HTML Issues

### ISSUE THREAD

**Issue by mgifford** [GSA/open-product-accessibility-template#87]
I did a quick evaluation with:
- https://www.npmjs.com/package/markdown
- https://www.npmjs.com/package/markdown-to-html

Both had issues, but markdown-to-html seemed to work better for most. 

Markdown is older and seems to have real problems with tables (and other things):
![markdown](https://user-images.githubusercontent.com/116832/128198788-2d2f8f47-44aa-4839-9a5d-58229cec0529.png)

Markdown-to-html seemed to have problems with lists inside of tables:
![markdown-to-html](https://user-images.githubusercontent.com/116832/128198801-bbfada36-dd74-41fd-b241-c33e57e01fc5.png)

I wondered if it might be easier to simply have the output from `npx ts-node src/opat.ts output -f opat/drupal-9.yaml -c catalog/2.4-edition-508-wcag-2.0.yaml -o drupal-9.markdown ` use 100% HTML for the tables rather than the pipe format from Markdown.

**Comment by dmundra** [comment]
Hi @mgifford, I am thinking in #15 and #16 we will have our own handlebars template for HTML with a lot more HTML options so we likely don't need to convert the markdown to HTML and the output itself with produce HTML.

**Comment by mgifford** [comment]
Brilliant..  I'll close this now then.  Handlebars rock!
